In [6]:
import numpy as np

a = np.array([i for i in range(10)])
a.shape
a.dtype

(10,)

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 基本属性

In [14]:
x.shape
X.shape

(3, 5)

In [15]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [16]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
n = 10
L = [i for i in range(n)]
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
A = [i*2 for i in L]
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]