In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X.shape, y.shape

((150, 4), (150,))

In [3]:
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 83, 119,  37,  43,  33,   1,  32,  46,  99,  50,  87, 104,  65,
       117, 106, 149, 139,  68,  57, 113, 131, 103,  58,  94,  60,  42,
        20,  11, 114,  85,  79,  61, 111, 142, 108,  29,  22,  34,  49,
        55,  19,  35,  15, 120,  97,  95,  24, 144,  96,  66, 127,   4,
        76,  45, 140,  78, 146,  10,   7,  25,  23, 102, 121, 124, 123,
         5,  39,   8, 145,  92, 133, 129, 109,  70, 125,  89,  54, 138,
        30, 148,  27, 126,  47,  56,  52, 134, 105, 130,  86,  90,  53,
         9,  41,  51,  62,  82, 136,  63,  91,  26,  64,  84,  80,   0,
         3, 147,  72, 112, 115, 110, 116,  28, 128,   6, 100,  40,  74,
       137,   2,  31,  59,  17, 141,  98,  69,  75,  48,  88,  71,  93,
        73, 135,  81,  14, 107,  12,  36, 143,  13,  77, 122,  16,  38,
       118,  21,  18, 132, 101,  67,  44])

In [4]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [5]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [6]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [7]:
X_train.shape, y_train.shape , X_test.shape, y_test.shape


((120, 4), (120,), (30, 4), (30,))

In [8]:
%run kNNClassifier.py

In [9]:
kNN = kNNClassifier(k=6)
kNN.fit(X_train, y_train)
y_predict = kNN.predict(X_test)

In [10]:
y_predict

array([2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
       1, 1, 0, 0, 0, 2, 1])

In [11]:
y_test

array([1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1,
       1, 1, 0, 0, 0, 2, 1])

In [28]:
votes = [y_predict[i]==y_test[i] for i in range(len(y_test))]
most_count = Counter(votes).most_common(1)[0][1]
accuracy = most_count/len(y_test)

In [29]:
accuracy

0.9333333333333333