In [42]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [43]:
boston = datasets.load_boston()

In [44]:
boston.data.shape, boston.target.shape

((506, 13), (506,))

In [45]:
import sys
sys.path.append(r"../")

In [46]:
from myML.LinearRegression import LinearRegression

In [47]:
X = boston.data
y = boston.target

X = X[y < 50]
y = y[y < 50]

In [48]:
from myML.preprocessing import train_test_split
X_train, y_train, X_test, y_test = train_test_split(X, y, seed=666)

In [57]:
reg = LinearRegression()
reg.fit_normal(X_train, y_train)

In [60]:
y_predict = reg.predict(X_test)

In [61]:
reg.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [62]:
reg.interception_

34.117399723201785

In [64]:
y_predict

array([18.08015868, 25.52447165, 12.98271397, 32.89477638, 24.17839745,
        2.66600125, 26.64297716, 32.23866352, 13.96590659, 24.0465123 ,
       14.92963   , 10.57419644, 30.28539981, 16.28302365, 23.67843428,
       25.63288299, 18.68105783, 24.01767076, 28.77234863, 26.9404495 ,
       12.87158142, 27.23259283, 26.07726096, 23.41270932, 20.80570812,
       31.96527196, 14.93177657, 20.94927605, 12.93149157, 29.8004438 ,
       35.29188752,  4.99369317, 13.10904465, 35.54982047, 16.00603155,
       21.53889058, 12.46701001, 29.12202629, 27.3433202 , 24.04852968,
       14.39961539, 23.61075774, 10.89223868, 22.38043687, 18.62604579,
       16.41773634, 24.43040765, 33.06929581, 19.19757395, 27.03634216,
       18.05693565, 14.90744724, 25.08683225, 16.09610653, 21.7469388 ,
       16.32259928, 24.25418684, 11.75290906, 27.91347808, 31.06610342,
       20.17028271, 24.99229322, 25.99180978, 12.11816691, 16.57739596,
       27.30354042, 22.26700274, 21.72088347, 31.5072238 , 14.09

In [65]:
y_test

array([18. , 24.8, 13.5, 34.9, 23.7, 13.8, 25.1, 28.5, 15.6, 33. , 16.2,
       16.3, 29.4, 17.8, 22.2, 20.6, 13.8, 19.4, 22.5, 23.9, 12.7, 24.8,
       23.9, 20.7, 23.2, 37.9, 13.5, 22.4, 12.3, 32.7, 43.1,  8.8, 12.8,
       41.7, 19.1, 21.7, 10.5, 24. , 27. , 23.1, 11. , 18.9, 15.2, 19.7,
       19.4, 14.3, 23.3, 31. , 19.8, 22.8, 19.6, 14.9, 24.7, 15.4, 19.6,
       18.9, 23. , 10.8, 28.6, 35.4, 18.8, 23.4, 22.6,  8.3, 12.7, 26.6,
       19.8, 18.9, 29. , 19. , 13. , 22.3, 22.8, 19.5, 14.1, 28.4, 20.1,
       13.9, 12. , 33.1, 38.7, 17.5, 19.9, 20.2, 29.6, 21.2, 21.6, 23.9,
       28.1, 20.4, 24.4, 35.4, 46. , 20.4, 16. , 31.5, 44. , 21. ])

In [67]:
from myML.metrics import r2_score

r2_score(y_test, y_predict)

0.8129794056212823

In [69]:
reg.score(X_test, y_test)

TypeError: predict() takes 2 positional arguments but 3 were given